---
# defaults file for node_exporter (systemd version)
 
node_exporter_user: "node_exporter"
node_exporter_version: "1.9.0"

# Architecture detection and mapping
node_exporter_arch_map:
  x86_64: "linux-amd64"
  aarch64: "linux-arm64"
  armv7l: "linux-armv7"
  armv6l: "linux-armv6"

node_exporter_arch: "{{ node_exporter_arch_map[ansible_architecture] | default('linux-amd64') }}"
node_exporter_download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.{{ node_exporter_arch }}.tar.gz"
node_exporter_extra_args: ""

# Service discovery configuration
node_exporter_service_discovery_enabled: true
node_exporter_prometheus_config_dir: "/opt/monitoring/prometheus/config"
node_exporter_prometheus_user_id: "65533"
node_exporter_prometheus_group_id: "65533" 