---
# defaults file for node_exporter (systemd version)
 
node_exporter_user: "node_exporter"
node_exporter_group: "node_exporter"
node_exporter_user_id: 9100
node_exporter_group_id: 9100
node_exporter_version: "1.9.0"

# Architecture detection and mapping
node_exporter_arch_map:
  x86_64: "linux-amd64"
  aarch64: "linux-arm64"


node_exporter_arch: "{{ node_exporter_arch_map[ansible_architecture] | default('linux-amd64') }}"
node_exporter_download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.{{ node_exporter_arch }}.tar.gz"
node_exporter_extra_args: "--collector.systemd --collector.loadavg"

# Service discovery configuration
node_exporter_service_discovery_enabled: true
node_exporter_prometheus_config_dir: "/opt/monitoring/prometheus/config"
# Prometheus user IDs for file ownership when creating service discovery files
node_exporter_prometheus_user_id: "65533"
node_exporter_prometheus_group_id: "65533"
# Whether this host should generate Prometheus file_sd targets locally (usually only the Prometheus host)
node_exporter_generate_prometheus_targets: false

# Security configuration - bind to localhost by default
node_exporter_bind_address: "0.0.0.0"
node_exporter_port: "9100"

# Networking / firewall configuration
node_exporter_monitoring_network_name: "monitoring"
node_exporter_manage_firewall: true
# Explicit allowed source CIDRs for accessing node_exporter (e.g., Prometheus VPN IP)
# Example: ['10.0.0.5/32']
node_exporter_allowed_sources: [10.0.0.0/24] 