---
# handlers file for cadvisor

- name: restart cadvisor
  community.docker.docker_compose_v2:
    project_name: "cadvisor"
    project_src: "{{ cadvisor_data_dir }}"
    state: restarted
  become: true
  listen: restart cadvisor
  when: not ansible_check_mode

- name: stop cadvisor
  community.docker.docker_compose_v2:
    project_name: "cadvisor"
    project_src: "{{ cadvisor_data_dir }}"
    state: stopped
  become: true
  listen: stop cadvisor
  when: not ansible_check_mode

- name: start cadvisor
  community.docker.docker_compose_v2:
    project_name: "cadvisor"
    project_src: "{{ cadvisor_data_dir }}"
    state: present
  become: true
  listen: start cadvisor
  when: not ansible_check_mode

- name: reload prometheus
  uri:
    url: "http://localhost:9090/-/reload"
    method: POST
    status_code: 200
  ignore_errors: true
  listen: reload prometheus 