---
# handlers file for cadvisor

- name: restart cadvisor
  command: docker compose restart
  args:
    chdir: "{{ cadvisor_data_dir }}"
  become: true
  listen: restart cadvisor
  when: not ansible_check_mode

- name: stop cadvisor
  command: docker compose down
  args:
    chdir: "{{ cadvisor_data_dir }}"
  become: true
  listen: stop cadvisor
  when: not ansible_check_mode

- name: start cadvisor
  command: docker compose up -d
  args:
    chdir: "{{ cadvisor_data_dir }}"
  become: true
  listen: start cadvisor
  when: not ansible_check_mode

- name: reload prometheus
  uri:
    url: "http://localhost:9090/-/reload"
    method: POST
    status_code: 200
  ignore_errors: true
  listen: reload prometheus 