---
# handlers file for traefik

- name: restart traefik
  community.docker.docker_compose_v2:
    project_name: "traefik"
    project_src: "{{ traefik_data_dir }}"
    state: restarted
  become: true
  listen: restart traefik
  when: not ansible_check_mode

- name: reload traefik
  command: docker compose kill -s USR1 traefik
  args:
    chdir: "{{ traefik_data_dir }}"
  become: true
  listen: reload traefik
  when: not ansible_check_mode

- name: stop traefik
  community.docker.docker_compose_v2:
    project_name: "traefik"
    project_src: "{{ traefik_data_dir }}"
    state: stopped
  become: true
  listen: stop traefik
  when: not ansible_check_mode

- name: start traefik
  community.docker.docker_compose_v2:
    project_name: "traefik"
    project_src: "{{ traefik_data_dir }}"
    state: present
  become: true
  listen: start traefik
  when: not ansible_check_mode 