---
# Validate required variables for Docker Registry
- name: Validate Docker Registry configuration variables
  include_tasks: "{{ role_path }}/../common/tasks/variable_validation.yml"
  vars:
    role_name: "docker-registry"
    required_variables:
      - "docker_registry_data_dir"
      - "docker_registry_s3_bucket"
      - "docker_registry_s3_region"
      - "docker_registry_s3_access_key"
      - "docker_registry_s3_secret_key"
    sensitive_variables:
      - "docker_registry_s3_access_key"
      - "docker_registry_s3_secret_key"
    custom_validations:
      - name: "docker_registry_data_dir"
        validation: "docker_registry_data_dir | regex_search('^/')"
        error_message: "docker_registry_data_dir must be an absolute path starting with '/'"
      - name: "docker_registry_port"
        validation: "docker_registry_port | int > 0 and docker_registry_port | int <= 65535"
        error_message: "docker_registry_port must be a valid port number (1-65535)"
      - name: "docker_registry_s3_bucket"
        validation: "docker_registry_s3_bucket | regex_search('^[a-z0-9.-]+$')"
        error_message: "docker_registry_s3_bucket must be a valid S3 bucket name (lowercase letters, numbers, dots, hyphens only)"

- name: Setup docker registry
  block:
    - name: Create docker registry data dir
      ansible.builtin.file:
        path: "{{ docker_registry_data_dir }}"
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Download Selectel CA certificate
      ansible.builtin.get_url:
        url: https://secure.globalsign.net/cacert/root-r6.crt
        dest: "{{ docker_registry_data_dir }}/root.crt.der"
        mode: '0644'

    - name: Convert certificate from DER to PEM
      ansible.builtin.command:
        cmd: openssl x509 -inform der -in {{ docker_registry_data_dir }}/root.crt.der -out {{ docker_registry_data_dir }}/root.crt
        creates: "{{ docker_registry_data_dir }}/root.crt"
      changed_when: false

    - name: Set certificate permissions
      ansible.builtin.file:
        path: "{{ docker_registry_data_dir }}/root.crt"
        mode: '0600'

    - name: Template docker-compose for docker registry
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: "{{ docker_registry_data_dir }}/docker-compose.yml"
      notify: Restart docker-registry

    - name: Start docker registry
      community.docker.docker_compose_v2:
        project_src: "{{ docker_registry_data_dir }}"
        state: present
      register: docker_registry_service
  when: not ansible_check_mode 