---
# handlers file for alertmanager

- name: restart alertmanager
  community.docker.docker_compose_v2:
    project_name: "alertmanager"
    project_src: "{{ alertmanager_data_dir }}"
    restarted: true
  become: true
  listen: restart alertmanager
  when: not ansible_check_mode

- name: stop alertmanager
  community.docker.docker_compose_v2:
    project_name: "alertmanager"
    project_src: "{{ alertmanager_data_dir }}"
    state: present
    stopped: true
  become: true
  listen: stop alertmanager
  when: not ansible_check_mode

- name: start alertmanager
  community.docker.docker_compose_v2:
    project_name: "alertmanager"
    project_src: "{{ alertmanager_data_dir }}"
    state: present
  become: true
  listen: start alertmanager
  when: not ansible_check_mode