---
- name: restart chronyd
  systemd:
    name: chronyd
    state: restarted
  become: true
  when: not ansible_check_mode and ansible_service_mgr is defined and ansible_service_mgr == "systemd"
  ignore_errors: true