---
# handlers file for wireguard_xray_gost_client

# Handler to save iptables rules (without Docker restart to avoid downtime)
- name: Save iptables rules
  listen: "commit iptables rules"
  shell: |
    mkdir -p /etc/iptables
    iptables-save > /etc/iptables/rules.v4
    ip6tables-save > /etc/iptables/rules.v6
  become: true

- name: Restart netfilter-persistent
  listen: "commit iptables rules"
  systemd:
    name: netfilter-persistent
    state: restarted
  become: true
  when: not ansible_check_mode and ansible_service_mgr is defined and ansible_service_mgr == "systemd"
  ignore_errors: true

- name: Restart xray
  systemd:
    name: xray
    state: restarted
    enabled: yes
  become: true
  when: not ansible_check_mode
  ignore_errors: true 