---
# handlers file for prometheus

- name: restart prometheus
  community.docker.docker_compose_v2:
    project_name: "prometheus"
    project_src: "{{ prometheus_data_dir }}"
    restarted: true
  become: true
  listen: restart prometheus
  when: not ansible_check_mode

- name: stop prometheus
  community.docker.docker_compose_v2:
    project_name: "prometheus"
    project_src: "{{ prometheus_data_dir }}"
    state: present
    stopped: true
  become: true
  listen: stop prometheus
  when: not ansible_check_mode

- name: start prometheus
  community.docker.docker_compose_v2:
    project_name: "prometheus"
    project_src: "{{ prometheus_data_dir }}"
    state: present
  become: true
  listen: start prometheus
  when: not ansible_check_mode

- name: reload prometheus
  uri:
    url: "http://localhost:9090/-/reload"
    method: POST
    status_code: [200]
  listen: reload prometheus
  when: not ansible_check_mode 