---
# tasks file for grafana

- name: Setup Grafana (standardized)
  include_tasks: "{{ role_path }}/../common/tasks/setup_service_user.yml"
  vars:
    service_name: "grafana"
    service_user: "{{ grafana_user }}"
    service_group: "{{ grafana_group }}"
    service_uid: "{{ grafana_user_id | default(omit) }}"
    service_gid: "{{ grafana_group_id | default(omit) }}"
    service_directories:
      - "{{ grafana_data_dir }}"
      - "{{ grafana_data_dir }}/provisioning"
      - "{{ grafana_data_dir }}/provisioning/datasources"
    directory_mode: "0755"
    # Use proper Grafana user ownership instead of root
    directory_owner: "{{ grafana_user_id }}"
    directory_group: "{{ grafana_group_id }}"
  when: not ansible_check_mode

- name: Deploy docker-compose.yml for grafana
  template:
    src: docker-compose.yml.j2
    dest: "{{ grafana_data_dir }}/docker-compose.yml"
    owner: "{{ grafana_user_id }}"
    group: "{{ grafana_group_id }}"
    mode: '0644'
  become: true
  tags: [configure, deploy]

- name: Start grafana with Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_data_dir }}"
    state: present
  become: true
  notify: restart grafana
  when: not ansible_check_mode
  tags: [deploy, start]

- name: Deploy Grafana provisioning for Prometheus datasource
  template:
    src: provisioning/datasources/prometheus.yml.j2
    dest: "{{ grafana_data_dir }}/provisioning/datasources/prometheus.yml"
    owner: "{{ grafana_user_id }}"
    group: "{{ grafana_group_id }}"
    mode: '0644'
  become: true
  notify: restart grafana 