---
# tasks file for grafana

- name: Setup Grafana
  block:
    - name: Create grafana group
      group:
        name: "{{ grafana_group }}"
        gid: "{{ grafana_group_id }}"
      become: true

    - name: Create grafana user
      user:
        name: "{{ grafana_user }}"
        group: "{{ grafana_group }}"
        uid: "{{ grafana_user_id }}"
        system: yes
        shell: /usr/sbin/nologin
        create_home: no
      become: true

    - name: Create grafana data directory
      file:
        path: "{{ grafana_data_dir }}"
        state: directory
        owner: "0"
        group: "0"
        mode: '0755'
      become: true

    - name: Create grafana provisioning directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "0"
        group: "0"
        mode: '0755'
      loop:
        - "{{ grafana_data_dir }}/provisioning"
        - "{{ grafana_data_dir }}/provisioning/datasources"
      become: true


  when: not ansible_check_mode

- name: Deploy docker-compose.yml for grafana
  template:
    src: docker-compose.yml.j2
    dest: "{{ grafana_data_dir }}/docker-compose.yml"
    owner: "0"
    group: "0"
    mode: '0644'
  become: true
  tags: [configure, deploy]

- name: Start grafana with Docker Compose
  command: docker compose up -d
  args:
    chdir: "{{ grafana_data_dir }}"
  become: true
  notify: restart grafana
  when: not ansible_check_mode
  tags: [deploy, start]

- name: Deploy Grafana provisioning for Prometheus datasource
  template:
    src: provisioning/datasources/prometheus.yml.j2
    dest: "{{ grafana_data_dir }}/provisioning/datasources/prometheus.yml"
    owner: "0"
    group: "0"
    mode: '0644'
  become: true
  notify: restart grafana 