---
# defaults file for jenkins-docker

# Jenkins Docker configuration
jenkins_image: "jenkins/jenkins:lts-jdk21"
jenkins_container_name: "jenkins"
jenkins_host_port: 8080
jenkins_agent_port: 50000
jenkins_domain: "jenkins.local"  # Domain name for Traefik routing

# Jenkins directories
jenkins_home: "/var/lib/jenkins"
jenkins_data_dir: "/opt/jenkins"


# User and group
jenkins_user: "jenkins"
jenkins_group: "jenkins"

# Default UID/GID for check mode - will be overridden by actual user creation
jenkins_uid: "1000"
jenkins_gid: "1001"

# Docker network
jenkins_network_name: "jenkins-network"

# SSL/TLS configuration
jenkins_use_ssl: false
jenkins_ssl_cert_path: ""
jenkins_ssl_key_path: ""
jenkins_verify_ssl_certs: false  # Set to false to skip SSL certificate validation during verification

# Environment variables
jenkins_java_opts: "-Xmx2048m -Djenkins.install.runSetupWizard=false -Dhudson.slaves.NodeProvisioner.initialDelay=0 -Dhudson.slaves.NodeProvisioner.MARGIN=50"
jenkins_opts: ""

# Plugin management
jenkins_install_plugins: true
jenkins_force_plugin_reinstall: false  # Set to true to clear plugins directory and force reinstall
jenkins_use_groovy_plugin_install: true
jenkins_plugin_installation_method: "groovy"  # Options: groovy, cli, or none
jenkins_plugins_list:
  - "ant"
  - "build-timeout"
  - "credentials-binding"
  - "email-ext"
  - "git"
  - "github-branch-source"
  - "gitlab-branch-source"
  - "gitlab-plugin"
  - "gitlab-webhook"
  - "gradle"
  - "ldap"
  - "mailer"
  - "matrix-auth"
  - "pam-auth"
  - "pipeline-build-step"
  - "pipeline-github-lib"
  - "pipeline-graph-analysis"
  - "pipeline-input-step"
  - "pipeline-milestone-step"
  - "pipeline-model-api"
  - "pipeline-model-definition"
  - "pipeline-model-extensions"
  - "pipeline-rest-api"
  - "pipeline-stage-step"
  - "pipeline-stage-tags-metadata"
  - "pipeline-stage-view"
  - "ssh-slaves"
  - "timestamper"
  - "workflow-aggregator"
  - "workflow-api"
  - "workflow-basic-steps"
  - "workflow-cps"
  - "workflow-cps-global-lib"
  - "workflow-durable-task-step"
  - "workflow-job"
  - "workflow-multibranch"
  - "workflow-scm-step"
  - "workflow-step-api"
  - "workflow-support"
  - "ws-cleanup"

# Security configuration
jenkins_admin_username: "admin"
# Default password - should be overridden in production for security
jenkins_admin_password: "changeme"
jenkins_disable_setup_wizard: true


# Internal variables (do not modify in inventory)
jenkins_version: "lts-jdk21"
jenkins_lts: true

# System requirements
minimum_disk_space_gb: 10
minimum_memory_mb: 2048

# Health check and verification configuration
jenkins_verification:
  enabled: true
  login_check:
    max_retries: 5
    retry_delay: 5  # Reduced from hardcoded 10 seconds
  api_check:
    max_retries: 10
    retry_delay: 10  # Reduced from hardcoded 15 seconds
  timeout: 300  # Total timeout in seconds

# Default security settings (internal)
jenkins_security_realm: "HudsonPrivateSecurityRealm"
jenkins_authorization_strategy: "FullControlOnceLoggedInAuthorizationStrategy"

# Plugin update center
jenkins_update_center_url: "https://updates.jenkins.io/update-center.json"

# Backup configuration
jenkins_backup_dir: "/opt/jenkins/backups"
jenkins_backup_retention_days: 7

# Traefik labels for Jenkins
jenkins_traefik_labels:
  - "traefik.enable=true"
  - "traefik.http.routers.jenkins.rule=Host(`{{ jenkins_domain }}`)"
  - "traefik.http.routers.jenkins.entrypoints=websecure"
  - "traefik.http.routers.jenkins.tls=true"
  - "traefik.http.routers.jenkins.middlewares=vpn-whitelist"
  - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
