---
# defaults file for dnsmasq
# NOTE: Some variables must be set in your playbook or inventory (see playbook example)

# DNS configuration
dnsmasq_conf_dir: "/etc/dnsmasq.d"
dnsmasq_conf_file: "/etc/dnsmasq.conf"
dnsmasq_user: "root"
dnsmasq_group: "root"

# DNS settings
# dnsmasq_domain: "" # Set in playbook or inventory
dnsmasq_server_ip: "10.0.0.1"
dnsmasq_upstream_dns:
  - "1.1.1.1"
  - "1.0.0.1"
  - "8.8.8.8"
  - "8.8.4.4"

# Host entries - for non-VPN related entries
dnsmasq_host_entries: [] 