---
# tasks file for fail2ban
- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
  become: true
  tags:
    - fail2ban

- name: Ensure fail2ban is running and enabled
  service:
    name: fail2ban
    state: started
    enabled: true
  become: true
  tags:
    - fail2ban

- name: Deploy fail2ban jail.local configuration
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: restart fail2ban
  become: true
  tags:
    - fail2ban

- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted
  become: true
  tags:
    - fail2ban
