---
# tasks file for fail2ban

- name: Setup fail2ban
  tags: [install, configure, security]
  block:
    - name: Install fail2ban
      apt:
        name: fail2ban
        state: present
      become: true
      tags: [install, security]

    - name: Ensure fail2ban is running and enabled
      systemd:
        name: fail2ban
        state: started
        enabled: true
      become: true
      tags: [install, security]

    - name: Restart fail2ban
      systemd:
        name: fail2ban
        state: restarted
      become: true
      tags: [install, security]
  when: not ansible_check_mode

- name: Deploy fail2ban jail.local configuration
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: restart fail2ban
  become: true
  tags:
    - fail2ban
