---
# Monitoring stack infrastructure validation tasks
# Only validates the infrastructure setup (network, directories) not services

- name: Check mode notice for validation
  debug:
    msg: "Running in check mode - validation tasks will be skipped. Infrastructure checks require actual execution."
  when: ansible_check_mode

- name: Verify monitoring network exists
  command: docker network inspect monitoring
  register: monitoring_network_check
  failed_when: false
  ignore_errors: true
  when: not ansible_check_mode

- name: Display monitoring network status
  debug:
    msg: "Monitoring network: {{ 'EXISTS' if (monitoring_network_check.rc is defined and monitoring_network_check.rc == 0) else 'MISSING' }}"

- name: Verify monitoring data directory exists
  stat:
    path: "{{ monitoring_stack.data_root }}"
  register: monitoring_data_dir_check
  when: not ansible_check_mode

- name: Display monitoring data directory status
  debug:
    msg: "Monitoring data directory: {{ 'EXISTS' if (monitoring_data_dir_check.stat is defined and monitoring_data_dir_check.stat.exists) else 'MISSING' }}"

- name: Summary of monitoring infrastructure validation
  debug:
    msg:
      - "=== Monitoring Infrastructure Validation Summary ==="
      - "Monitoring Network: {{ 'EXISTS' if (monitoring_network_check.rc is defined and monitoring_network_check.rc == 0) else 'MISSING' }}"
      - "Data Directory: {{ 'EXISTS' if (monitoring_data_dir_check.stat is defined and monitoring_data_dir_check.stat.exists) else 'MISSING' }}"

- name: Fail if critical infrastructure is missing
  fail:
    msg: "Critical monitoring infrastructure is missing. Check the logs for details."
  when: >
    (monitoring_network_check.rc is defined and monitoring_network_check.rc != 0) or
    (monitoring_data_dir_check.stat is defined and not monitoring_data_dir_check.stat.exists)
  ignore_errors: true