---
# handlers file for loki

- name: restart loki
  community.docker.docker_compose_v2:
    project_name: "loki"
    project_src: "{{ loki_data_dir }}"
    state: restarted
  become: true
  listen: restart loki
  when: not ansible_check_mode

- name: stop loki
  community.docker.docker_compose_v2:
    project_name: "loki"
    project_src: "{{ loki_data_dir }}"
    state: stopped
  become: true
  listen: stop loki
  when: not ansible_check_mode

- name: start loki
  community.docker.docker_compose_v2:
    project_name: "loki"
    project_src: "{{ loki_data_dir }}"
    state: present
  become: true
  listen: start loki
  when: not ansible_check_mode

- name: reload prometheus
  uri:
    url: "{{ loki_prometheus_reload_url | default('http://localhost:9090/-/reload') }}"
    method: POST
    status_code: 200
  listen: reload prometheus
  when: loki_notify_prometheus_reload | default(false)
  ignore_errors: true 