---
# handlers file for loki

- name: restart loki
  command: docker compose restart
  args:
    chdir: "{{ loki_data_dir }}"
  become: true
  listen: restart loki

- name: stop loki
  command: docker compose down
  args:
    chdir: "{{ loki_data_dir }}"
  become: true
  listen: stop loki

- name: start loki
  command: docker compose up -d
  args:
    chdir: "{{ loki_data_dir }}"
  become: true
  listen: start loki 