---
# tasks file for alertmanager

- name: Setup Alertmanager
  block:
    - name: Setup Alertmanager user and directories (standardized)
      include_tasks: "{{ role_path }}/../common/tasks/setup_service_user.yml"
      vars:
        service_name: "alertmanager"
        service_user: "{{ alertmanager_user }}"
        service_group: "{{ alertmanager_group }}"
        service_uid: "{{ alertmanager_user_id | default(omit) }}"
        service_gid: "{{ alertmanager_group_id | default(omit) }}"
        service_directories:
          - "{{ alertmanager_data_dir }}"
          - "{{ alertmanager_data_dir }}/data"
        directory_mode: "0755"



    # Deploy sample alert rules
    - name: Create Prometheus rules directory
      file:
        path: "{{ alertmanager_prometheus_rules_dir }}"
        state: directory
        owner: "{{ alertmanager_prometheus_user_id }}"
        group: "{{ alertmanager_prometheus_group_id }}"
        mode: '0755'
      become: true

    - name: Deploy sample alert rules
      copy:
        src: sample_alerts.yml
        dest: "{{ alertmanager_prometheus_rules_dir }}/sample_alerts.yml"
        owner: "{{ alertmanager_prometheus_user_id }}"
        group: "{{ alertmanager_prometheus_group_id }}"
        mode: '0644'
      become: true
      notify: restart prometheus
  when: not ansible_check_mode

- name: Deploy alertmanager configuration
  template:
    src: alertmanager.yml.j2
    dest: "{{ alertmanager_data_dir }}/alertmanager.yml"
    owner: "{{ alertmanager_user_id }}"
    group: "{{ alertmanager_group_id }}"
    mode: '0644'
  become: true
  notify: restart alertmanager

- name: Deploy docker-compose.yml for alertmanager
  template:
    src: docker-compose.yml.j2
    dest: "{{ alertmanager_data_dir }}/docker-compose.yml"
    owner: "{{ alertmanager_user_id }}"
    group: "{{ alertmanager_group_id }}"
    mode: '0644'
  become: true
  tags: [configure, deploy]

- name: Start alertmanager with Docker Compose
  command: docker compose up -d
  args:
    chdir: "{{ alertmanager_data_dir }}"
  become: true
  notify: restart alertmanager
  when: not ansible_check_mode
  tags: [deploy, start]

# Register alertmanager endpoint for prometheus configuration
- name: Register alertmanager endpoint
  set_fact:
    monitoring_alertmanagers: "{{ monitoring_alertmanagers | default([]) + [{'static_configs': [{'targets': ['alertmanager:9093']}]}] }}" 