---
- name: Deploy Alertmanager with Telegram Notifications
  hosts: monitoring_servers
  become: true

  vars:
    # Email configuration - disabled (leave empty to use only Telegram)
    alertmanager_email_smtp: ""
    alertmanager_email_from: ""
    alertmanager_email_to: ""
    alertmanager_email_auth_username: ""
    alertmanager_email_auth_password: ""

    # Telegram configuration
    alertmanager_telegram_bot_token: "your_bot_token"
    alertmanager_telegram_chat_id: "your_chat_id"

    # Alert routing configuration
    alertmanager_route_group_wait: "30s"
    alertmanager_route_group_interval: "5m"
    alertmanager_route_repeat_interval: "4h"
  
  roles:
    - common
    - monitoring-stack  # Create monitoring network first
    - prometheus        # Then prometheus
    - alertmanager      # Finally alertmanager 