---
# Playbook: fail2ban.yml
# Description: Configures fail2ban intrusion prevention
# Usage: ansible-playbook -i inventory.yml playbooks/fail2ban.yml

- name: Configure fail2ban on servers
  hosts: all
  become: true
  vars:
    fail2ban_enable_nginx: false
  roles:
    - fail2ban
  post_tasks:
    - name: Verify fail2ban status
      command: fail2ban-client status
      register: fail2ban_status
      changed_when: false
      failed_when: fail2ban_status.rc != 0
