---
- name: Deploy Restic Exporter for Prometheus Monitoring
  hosts: all
  become: yes
  
  vars:
    # REQUIRED: Set your Restic repository configuration
    # Choose one of the following repository types:
    
    # For S3-compatible storage (AWS S3, MinIO, Wasabi, etc.)
    restic_exporter_restic_repository: "s3:s3.amazonaws.com/bucket-name"
    restic_exporter_restic_password: ""  # Set your repository password
    restic_exporter_aws_access_key_id: ""  # Set your AWS access key
    restic_exporter_aws_secret_access_key: ""  # Set your AWS secret key
    
    # For Backblaze B2
    # restic_exporter_restic_repository: "b2:bucketname:path/to/repo"
    # restic_exporter_restic_password: ""  # Set your repository password
    # restic_exporter_b2_account_id: ""  # Set your B2 account ID
    # restic_exporter_b2_account_key: ""  # Set your B2 account key
    
    # For local repository
    # restic_exporter_restic_repository: "/data"
    # restic_exporter_restic_password: ""  # Set your repository password
    
    # For REST server
    # restic_exporter_restic_repository: "rest:http://user:password@127.0.0.1:8000/"
    # restic_exporter_restic_password: ""  # Set your repository password
    
    # Optional: Customize volume mounts
    # Adjust the host path to match your Restic repository location
    restic_exporter_volumes:
      - "/backup/restic-repo:/data:ro"  # Example: local repository
      # - "/etc/restic:/etc/restic:ro"  # Example: config directory
    
    # Optional: Customize refresh interval (in seconds)
    # WARNING: Lower values increase costs for remote repositories
    restic_exporter_environment:
      TZ: "UTC"
      REFRESH_INTERVAL: "1800"  # 30 minutes - recommended for most use cases
      LOG_LEVEL: "INFO"
      EXIT_ON_ERROR: "False"
      NO_CHECK: "False"
      NO_STATS: "False"
      NO_LOCKS: "False"
      INCLUDE_PATHS: "False"
      INSECURE_TLS: "False"
    
    # Optional: Customize container settings
    restic_exporter_port: 8001
    restic_exporter_container_name: "restic-exporter"
    restic_exporter_restart_policy: "unless-stopped"
    
    # Optional: Customize health check settings
    restic_exporter_health_check_enabled: true
    restic_exporter_health_check_interval: "30s"
    restic_exporter_health_check_timeout: "10s"
    restic_exporter_health_check_retries: 3

  pre_tasks:
    - name: Validate required variables
      fail:
        msg: |
          Required variables not set:
          - restic_exporter_restic_repository: {{ restic_exporter_restic_repository | default('NOT SET') }}
          - restic_exporter_restic_password: {{ restic_exporter_restic_password | default('NOT SET') }}
          
          For S3: Also set restic_exporter_aws_access_key_id and restic_exporter_aws_secret_access_key
          For B2: Also set restic_exporter_b2_account_id and restic_exporter_b2_account_key
      when: 
        - restic_exporter_restic_repository == "" or restic_exporter_restic_repository is not defined
        - restic_exporter_restic_password == "" or restic_exporter_restic_password is not defined

  roles:
    - restic-exporter

  post_tasks:
    - name: Display deployment summary
      debug:
        msg: |
          Restic Exporter deployment completed successfully!
          
          Configuration:
          - Repository: {{ restic_exporter_restic_repository }}
          - Port: {{ restic_exporter_port }}
          - Container: {{ restic_exporter_container_name }}
          - Refresh Interval: {{ restic_exporter_environment.REFRESH_INTERVAL }} seconds
          
          Next steps:
          1. Verify metrics endpoint: curl http://localhost:{{ restic_exporter_port }}/metrics
          2. Add to Prometheus config (job_name: restic-exporter)
          3. Import Grafana dashboard from restic-exporter repository
          4. Set up alerts for backup failures and outdated backups
          
          Available metrics:
          - restic_check_success: Repository health status
          - restic_snapshots_total: Total snapshots count
          - restic_backup_timestamp: Last backup timestamp
          - restic_backup_files_total: Files in backup
          - restic_backup_size_total: Backup size in bytes
          - restic_locks_total: Repository locks count
