---
# Handlers for traditional WireGuard configuration

- name: restart wireguard
  ansible.builtin.systemd:
    name: "wg-quick@{{ wireguard_interface }}"
    state: restarted
  become: true
  when: not ansible_check_mode

- name: restart dnsmasq
  ansible.builtin.systemd:
    name: dnsmasq
    state: restarted
  become: true
  when: not ansible_check_mode
