---
# Validate required variables for Portainer Agent
- name: Validate Portainer Agent configuration variables
  include_tasks: "{{ role_path }}/../common/tasks/variable_validation.yml"
  vars:
    role_name: "portainer-agent"
    required_variables:
      - "portainer_agent_data_directory"
      - "portainer_agent_compose_dir"
      - "portainer_agent_port"
    sensitive_variables:
      - "portainer_agent_edge_key"
    conditional_variables:
      - condition: "portainer_agent_edge | default(false)"
        variables:
          - "portainer_agent_edge_key"
          - "portainer_agent_edge_id"
    custom_validations:
      - name: "portainer_agent_data_directory"
        validation: "portainer_agent_data_directory | regex_search('^/')"
        error_message: "portainer_agent_data_directory must be an absolute path starting with '/'"
      - name: "portainer_agent_compose_dir"
        validation: "portainer_agent_compose_dir | regex_search('^/')"
        error_message: "portainer_agent_compose_dir must be an absolute path starting with '/'"
      - name: "portainer_agent_port"
        validation: "portainer_agent_port | int > 0 and portainer_agent_port | int <= 65535"
        error_message: "portainer_agent_port must be a valid port number (1-65535)"

- name: Setup Portainer Agent
  block:
    - name: Create portainer agent data directory
      ansible.builtin.file:
        path: "{{ portainer_agent_data_directory }}"
        state: directory
        mode: "0755"
        owner: "{{ portainer_agent_user }}"
        group: "{{ portainer_agent_group }}"

    - name: Create portainer agent compose directory
      ansible.builtin.file:
        path: "{{ portainer_agent_compose_dir }}"
        state: directory
        mode: "0755"
        owner: "{{ portainer_agent_user }}"
        group: "{{ portainer_agent_group }}"
  when: not ansible_check_mode

- name: Create portainer agent docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ portainer_agent_compose_path }}"
    mode: "0644"
    owner: "{{ portainer_agent_user }}"
    group: "{{ portainer_agent_group }}" 

- name: Start portainer agent container
  community.docker.docker_compose_v2:
    project_src: "{{ portainer_agent_compose_dir }}"
    state: present
  when: not ansible_check_mode