---
- name: Create portainer agent data directory
  ansible.builtin.file:
    path: "{{ portainer_agent_data_directory }}"
    state: directory
    mode: "0755"
    owner: "{{ portainer_agent_user }}"
    group: "{{ portainer_agent_group }}"

- name: Create portainer agent compose directory
  ansible.builtin.file:
    path: "{{ portainer_agent_compose_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ portainer_agent_user }}"
    group: "{{ portainer_agent_group }}"

- name: Create portainer agent docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ portainer_agent_compose_path }}"
    mode: "0644"
    owner: "{{ portainer_agent_user }}"
    group: "{{ portainer_agent_group }}"

- name: Start portainer agent container
  community.docker.docker_compose_v2:
    project_src: "{{ portainer_agent_compose_dir }}"
    state: present 