---
# handlers file for node_exporter

- name: restart node_exporter
  systemd:
    name: node_exporter
    state: restarted
  become: true
  listen: restart node_exporter
  when: not ansible_check_mode
  ignore_errors: true

- name: stop node_exporter
  systemd:
    name: node_exporter
    state: stopped
  become: true
  listen: stop node_exporter
  when: not ansible_check_mode
  ignore_errors: true

- name: start node_exporter
  systemd:
    name: node_exporter
    state: started
  become: true
  listen: start node_exporter
  when: not ansible_check_mode
  ignore_errors: true 