---
# Meta role for setting up monitoring infrastructure
# This role only handles the foundational infrastructure (network, directories)
# Individual monitoring roles should be run separately after this

dependencies:
  # Only common foundation - no monitoring roles to avoid circular dependencies
  - role: common
    tags: ["common", "monitoring"]