---
# defaults file for jenkins-ssh-agent-docker

# Jenkins SSH Agent Docker configuration
jenkins_ssh_agent_image: "jenkins/ssh-agent:jdk21"
jenkins_ssh_agent_container_name: "jenkins-ssh-agent"

# Docker configuration
jenkins_docker_gid: 988  # Default Docker GID, should be overridden with actual host GID

# SSH key configuration
jenkins_ssh_key_path: "/opt/jenkins/ssh"
jenkins_ssh_key_name: "jenkins_agent_key"
jenkins_ssh_key_type: "rsa"
jenkins_ssh_key_bits: 4096
jenkins_ssh_key_comment: "jenkins-agent"

# SSH public key (will be populated during execution, default for check mode)
jenkins_ssh_public_key: "{{ ansible_check_mode | ternary('CHECK_MODE_PLACEHOLDER', '') }}"

# Jenkins master connection settings
jenkins_master_url: "http://jenkins:8080"
jenkins_ssh_agent_name: "docker-ssh-agent"
jenkins_ssh_agent_workdir: "/home/jenkins/agent"

# Docker network configuration
jenkins_network_name: "jenkins-network"

# Docker Compose path
jenkins_compose_path: "/opt/jenkins/ssh-agent"

# Docker volume mounts
jenkins_ssh_agent_volumes:
  - "/var/run/docker.sock:/var/run/docker.sock"
  - "/tmp:/tmp"
  - "/data:/data"

# Restart policy
jenkins_ssh_agent_restart_policy: "always"

# Pull image on each deployment
jenkins_ssh_agent_force_pull: true

# SSH server configuration
jenkins_ssh_port: 22
jenkins_ssh_user: "jenkins" 