---
# tasks file for blackbox_exporter

- name: Setup Blackbox Exporter user and directories (standardized)
  include_tasks: "{{ role_path }}/../common/tasks/setup_service_user.yml"
  vars:
    service_name: "blackbox_exporter"
    service_user: "{{ blackbox_exporter_user }}"
    service_group: "{{ blackbox_exporter_group }}"
    service_directories:
      - "{{ blackbox_exporter_data_dir }}"
    directory_mode: "0755"
  when: not ansible_check_mode
  tags: [install, configure]

- name: Deploy blackbox_exporter config
  template:
    src: blackbox.yml.j2
    dest: "{{ blackbox_exporter_data_dir }}/blackbox.yml"
    owner: "{{ blackbox_exporter_user }}"
    group: "{{ blackbox_exporter_group }}"
    mode: '0644'
  become: true

- name: Deploy endpoints configuration
  template:
    src: endpoints.yml.j2
    dest: "{{ blackbox_endpoints_config_file }}"
    owner: "{{ blackbox_exporter_user }}"
    group: "{{ blackbox_exporter_group }}"
    mode: '0644'
  become: true
  when: blackbox_enable_website_monitoring | default(false)

- name: Deploy docker-compose.yml for blackbox_exporter
  template:
    src: docker-compose.yml.j2
    dest: "{{ blackbox_exporter_data_dir }}/docker-compose.yml"
    owner: "{{ blackbox_exporter_user }}"
    group: "{{ blackbox_exporter_group }}"
    mode: '0644'
  become: true
  tags: [configure, deploy]

# Create service discovery file for Prometheus to pick up automatically
- name: Create blackbox targets service discovery file
  template:
    src: blackbox_targets.yml.j2
    dest: "{{ blackbox_exporter_prometheus_config_dir }}/targets/blackbox_targets.yml"
    owner: "{{ blackbox_exporter_prometheus_user_id }}"
    group: "{{ blackbox_exporter_prometheus_group_id }}"
    mode: '0644'
  become: true
  when: blackbox_endpoints is defined and blackbox_endpoints | length > 0
  tags: [configure, deploy]

- name: Deploy Blackbox Exporter with standardized Docker Compose
  include_tasks: "{{ role_path }}/../common/tasks/docker_compose_deploy.yml"
  vars:
    compose_project_name: "blackbox_exporter"
    compose_project_src: "{{ blackbox_exporter_data_dir }}"
    compose_pull: always
    compose_remove_orphans: true
  when: not ansible_check_mode
  tags: [deploy, start]

# Register blackbox targets for prometheus configuration
- name: Register blackbox targets
  set_fact:
    prometheus_blackbox_targets: "{{ blackbox_endpoints | map(attribute='url') | list }}"
    monitoring_scrape_configs: "{{ monitoring_scrape_configs | default([]) + [blackbox_scrape_config] }}"
  vars:
    blackbox_scrape_config:
      job_name: 'blackbox_targets'
      metrics_path: /probe
      params:
        module: [http_2xx]
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox_exporter:9115
        - source_labels: [__param_target]
          regex: '(.*)'
          target_label: target
      static_configs:
        - targets: "{{ blackbox_endpoints | map(attribute='url') | list }}"
  when: blackbox_endpoints is defined and blackbox_endpoints | length > 0 