---
# tasks file for prometheus

- name: Ensure monitoring network exists
  community.docker.docker_network:
    name: "{{ monitoring_stack.network_name }}"
    state: present
  become: true
  when: not ansible_check_mode
  tags: [install, configure]

- name: Detect Docker gateway IP for node_exporter connectivity
  shell: |
    # Try to get the gateway IP of the monitoring network
    docker network inspect {{ monitoring_stack.network_name }} --format '{% raw %}{{range .IPAM.Config}}{{.Gateway}}{{end}}{% endraw %}' 2>/dev/null || \
    # Fallback to default bridge network gateway
    docker network inspect bridge --format '{% raw %}{{range .IPAM.Config}}{{.Gateway}}{{end}}{% endraw %}' 2>/dev/null || \
    # Final fallback
    echo "172.17.0.1"
  register: docker_gateway_ip
  become: true
  when: not ansible_check_mode
  tags: [configure]

- name: Set node_exporter target IP
  set_fact:
    prometheus_node_exporter_target: "{{ docker_gateway_ip.stdout | default('host.docker.internal') }}:9100"
  when: not ansible_check_mode
  tags: [configure]

# Note: Firewall configuration is handled centrally by the monitoring-stack role
# to ensure proper iptables rules and avoid conflicts between individual roles.

- name: Setup Prometheus user and directories
  block:
    - name: Create Prometheus group
      group:
        name: "{{ prometheus_group }}"
        gid: "{{ prometheus_group_id }}"
      become: true
      tags: [install, configure]

    - name: Create Prometheus user
      user:
        name: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        uid: "{{ prometheus_user_id }}"
        system: yes
        shell: /usr/sbin/nologin
        create_home: no
      become: true
      tags: [install, configure]

    - name: Create Prometheus directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ prometheus_user_id }}"
        group: "{{ prometheus_group_id }}"
        mode: '0755'
      loop:
        - "{{ prometheus_data_dir }}"
        - "{{ prometheus_data_dir }}/data"
        - "{{ prometheus_config_dir }}"
        - "{{ prometheus_rules_dir }}"
        - "{{ prometheus_alerts_dir }}"
        - "{{ prometheus_config_dir }}/targets"  # For file-based service discovery
      become: true
      tags: [install, configure]

    - name: Ensure data directory has correct permissions
      file:
        path: "{{ prometheus_data_dir }}/data"
        owner: "{{ prometheus_user_id }}"
        group: "{{ prometheus_group_id }}"
        mode: '0755'
        recurse: yes
      become: true
      tags: [install, configure]
  when: not ansible_check_mode
  tags: [install, configure]

- name: Deploy docker-compose.yml for Prometheus
  template:
    src: docker-compose.yml.j2
    dest: "{{ prometheus_data_dir }}/docker-compose.yml"
    owner: "{{ prometheus_user_id }}"
    group: "{{ prometheus_group_id }}"
    mode: '0644'
  become: true
  tags: [configure, deploy]

- name: Deploy prometheus.yml config
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: "{{ prometheus_user_id }}"
    group: "{{ prometheus_group_id }}"
    mode: '0644'
  become: true
  tags: [configure, deploy]

- name: Deploy Loki targets for file-based service discovery
  template:
    src: loki_targets.yml.j2
    dest: "{{ prometheus_config_dir }}/targets/loki_targets.yml"
    owner: "{{ prometheus_user_id }}"
    group: "{{ prometheus_group_id }}"
    mode: '0644'
  notify: reload prometheus
  tags: [configure, deploy]

# Deploy retention monitoring and management
- name: Deploy retention alert rules
  copy:
    src: retention_alerts.yml
    dest: "{{ prometheus_rules_dir }}/retention_alerts.yml"
    owner: "{{ prometheus_user_id }}"
    group: "{{ prometheus_group_id }}"
    mode: '0644'
  notify: reload prometheus
  tags: [configure, deploy]

- name: Start Prometheus with Docker Compose
  command: docker compose up -d
  args:
    chdir: "{{ prometheus_data_dir }}"
  become: true
  notify: restart prometheus
  when: not ansible_check_mode
  tags: [deploy, start]

- name: Deploy retention cleanup script
  copy:
    src: cleanup_retention.sh
    dest: "{{ prometheus_data_dir }}/cleanup_retention.sh"
    owner: "{{ prometheus_user_id }}"
    group: "{{ prometheus_group_id }}"
    mode: '0755'
  become: true
  tags: [configure, deploy]

- name: Create retention cleanup symlink
  file:
    src: "{{ prometheus_data_dir }}/cleanup_retention.sh"
    dest: "/usr/local/bin/cleanup-monitoring-retention"
    state: link
  become: true
  when: not ansible_check_mode
  tags: [configure, deploy]

# Create retention monitoring cron job
- name: Create retention monitoring cron job
  cron:
    name: "Monitor retention and cleanup"
    minute: "0"
    hour: "2"
    job: "{{ prometheus_data_dir }}/cleanup_retention.sh --check >> /var/log/monitoring-retention.log 2>&1"
    user: "{{ prometheus_user }}"
  become: true
  when: prometheus_retention.cleanup.enabled | default(true) and not ansible_check_mode
  tags: [configure, deploy]

# Verify retention configuration
- name: Wait for Prometheus to be ready (standardized health check)
  include_tasks: "{{ role_path }}/../common/tasks/service_health_check.yml"
  vars:
    service_name: "prometheus"
    service_url: "http://localhost:9090/-/ready"
    service_port: 9090
    expected_status_codes: [200]
    max_retries: 30
    retry_delay: 10
    service_container_name: "prometheus"
    ignore_health_check_failures: true  # This is a validation step
  when: not ansible_check_mode
  tags: [validate]

- name: Check Prometheus retention configuration
  include_tasks: "{{ role_path }}/../common/tasks/network_retry.yml"
  vars:
    operation_name: "Prometheus runtime info query"
    operation_url: "http://localhost:9090/api/v1/status/runtimeinfo"
    operation_method: "GET"
    max_retries: 5
    retry_delay: 5
    ignore_network_failures: true  # This is validation, not critical
  register: prometheus_runtime_info
  when: not ansible_check_mode
  tags: [validate]

- name: Display Prometheus retention settings
  debug:
    msg:
      - "Prometheus retention configuration:"
      - "Time retention: {{ prometheus_retention.time }}"
      - "Size retention: {{ prometheus_retention.size }}"
      - "Runtime retention: {{ prometheus_runtime_info.json.data.storageRetention | default('Not available') }}"
  when: prometheus_runtime_info.json is defined and not ansible_check_mode
  tags: [validate] 