groups:
  - name: container_resource_alerts
    rules:
      # Container CPU Alerts
      - alert: ContainerHighCPUUsage
        expr: rate(container_cpu_usage_seconds_total{job="cadvisor", environment="prod", namespace=~"prod-.*", container!~"redis.*|test.*"}[5m]) * 100 > 80
        for: 2m  
        labels:
          severity: warning
          service: container-monitoring
        annotations:
          summary: "Container {{ $labels.container }} high CPU usage"
          description: "Container {{ $labels.container }} in namespace {{ $labels.namespace }} on {{ $labels.instance }} has CPU usage at {{ $value | printf \"%.2f\" }}% for more than 2 minutes."
      - alert: ContainerCriticalCPUUsage
        expr: rate(container_cpu_usage_seconds_total{job="cadvisor", environment="prod", namespace=~"prod-.*", container!~"redis.*|test.*"}[5m]) * 100 > 95
        for: 1m  
        labels:
          severity: critical
          service: container-monitoring
        annotations:
          summary: "Container {{ $labels.container }} critical CPU usage"
          description: "Container {{ $labels.container }} in namespace {{ $labels.namespace }} on {{ $labels.instance }} has CPU usage at {{ $value | printf \"%.2f\" }}% for more than 1 minute. Immediate action required."
      # Container Memory Alerts
      - alert: ContainerHighMemoryUsage
        expr: (container_memory_usage_bytes{job="cadvisor", environment="prod", namespace=~"prod-.*", container!~"redis.*|test.*"} / container_spec_memory_limit_bytes{job="cadvisor", environment="prod", namespace=~"prod-.*", container!~"redis.*|test.*"}) * 100 > 85 and container_spec_memory_limit_bytes{job="cadvisor", environment="prod", namespace=~"prod-.*", container!~"redis.*|test.*"} > 0
        for: 2m  
        labels:
          severity: warning
          service: container-monitoring
        annotations:
          summary: "Container {{ $labels.container }} high memory usage"
          description: "Container {{ $labels.container }} in namespace {{ $labels.namespace }} on {{ $labels.instance }} has memory usage at {{ $value | printf \"%.2f\" }}% of limit for more than 2 minutes."
      - alert: ContainerCriticalMemoryUsage
        expr: (container_memory_usage_bytes{job="cadvisor", environment="prod", namespace=~"prod-.*", container!~"redis.*|test.*"} / container_spec_memory_limit_bytes{job="cadvisor", environment="prod", namespace=~"prod-.*", container!~"redis.*|test.*"}) * 100 > 95 and container_spec_memory_limit_bytes{job="cadvisor", environment="prod", namespace=~"prod-.*", container!~"redis.*|test.*"} > 0
        for: 1m  
        labels:
          severity: critical
          service: container-monitoring
        annotations:
          summary: "Container {{ $labels.container }} critical memory usage"
          description: "Container {{ $labels.container }} in namespace {{ $labels.namespace }} on {{ $labels.instance }} has memory usage at {{ $value | printf \"%.2f\" }}% of limit for more than 1 minute. Immediate action required."
      # Container Memory Limit Alerts
      - alert: ContainerMemoryLimitReached
        expr: container_memory_usage_bytes{job="cadvisor", environment="prod", namespace=~"prod-.*", container!~"redis.*|test.*"} >= container_spec_memory_limit_bytes{job="cadvisor", environment="prod", namespace=~"prod-.*", container!~"redis.*|test.*"} and container_spec_memory_limit_bytes{job="cadvisor", environment="prod", namespace=~"prod-.*", container!~"redis.*|test.*"} > 0
        for: 15s  
        labels:
          severity: critical
          service: container-monitoring
        annotations:
          summary: "Container {{ $labels.container }} memory limit reached"
          description: "Container {{ $labels.container }} in namespace {{ $labels.namespace }} on {{ $labels.instance }} has reached its memory limit and may be killed by OOMKiller."
      # Container Disk I/O Alerts
      - alert: ContainerHighDiskIO
        expr: (rate(container_fs_reads_bytes_total{job="cadvisor", environment="prod", namespace=~"prod-.*", container!~"redis.*|test.*"}[5m]) + rate(container_fs_writes_bytes_total{job="cadvisor", environment="prod", namespace=~"prod-.*", container!~"redis.*|test.*"}[5m])) > 100 * 1024 * 1024
        for: 2m  
        labels:
          severity: warning
          service: container-monitoring
        annotations:
          summary: "Container {{ $labels.container }} high disk I/O"
          description: "Container {{ $labels.container }} in namespace {{ $labels.namespace }} on {{ $labels.instance }} has high disk I/O at {{ $value | printf \"%.0f\" }} bytes/s for more than 2 minutes."
      # Container Network Alerts
      - alert: ContainerHighNetworkIO
        expr: (rate(container_network_receive_bytes_total{job="cadvisor", environment="prod", namespace=~"prod-.*", container!~"redis.*|test.*"}[5m]) + rate(container_network_transmit_bytes_total{job="cadvisor", environment="prod", namespace=~"prod-.*", container!~"redis.*|test.*"}[5m])) > 100 * 1024 * 1024
        for: 2m  
        labels:
          severity: warning
          service: container-monitoring
        annotations:
          summary: "Container {{ $labels.container }} high network I/O"
          description: "Container {{ $labels.container }} in namespace {{ $labels.namespace }} on {{ $labels.instance }} has high network I/O at {{ $value | printf \"%.0f\" }} bytes/s for more than 2 minutes."

  - name: container_availability_alerts
    rules:
      # Container Restart Alerts
      - alert: ContainerRestartTooOften
        expr: rate(container_status_restarts_total{job="cadvisor", environment="prod", namespace=~"prod-.*", container!~"redis.*|test.*"}[5m]) > 0
        for: 2m  
        labels:
          severity: warning
          service: container-monitoring
        annotations:
          summary: "Container {{ $labels.container }} restarting frequently"
          description: "Container {{ $labels.container }} in namespace {{ $labels.namespace }} on {{ $labels.instance }} is restarting at {{ $value | printf \"%.2f\" }} restarts/sec. Check container logs for issues."
      # Container Exit Code Alerts
      - alert: ContainerExitedWithError
        expr: min_over_time(kube_pod_container_status_terminated{job="kube-state-metrics", environment="prod", namespace=~"prod-.*", container!~"redis.*|test.*"}[5m]) == 1
        for: 15s  
        labels:
          severity: warning
          service: container-monitoring
        annotations:
          summary: "Container {{ $labels.container }} exited with error"
          description: "Container {{ $labels.container }} in namespace {{ $labels.namespace }} on {{ $labels.instance }} has terminated. Check container logs."
      # Container State Alerts
      - alert: ContainerNotRunning
        expr: absent(container_last_seen{job="cadvisor", environment="prod", namespace=~"prod-.*", container!~"redis.*|test.*", status="running"}) or min_over_time(container_last_seen{job="cadvisor", environment="prod", namespace=~"prod-.*", container!~"redis.*|test.*", status="running"}[5m]) == 0
        for: 2m  
        labels:
          severity: critical
          service: container-monitoring
        annotations:
          summary: "Container {{ $labels.container }} not running"
          description: "Container {{ $labels.container }} in namespace {{ $labels.namespace }} on {{ $labels.instance }} has not been seen in running state for more than 2 minutes."

  - name: container_performance_alerts
    rules:
      # Container Throttling Alerts
      - alert: ContainerCPUThrottling
        expr: rate(container_cpu_cfs_throttled_seconds_total{job="cadvisor", environment="prod", namespace=~"prod-.*", container!~"redis.*|test.*"}[5m]) > 0.01
        for: 2m  
        labels:
          severity: warning
          service: container-monitoring
        annotations:
          summary: "Container {{ $labels.container }} CPU throttling"
          description: "Container {{ $labels.container }} in namespace {{ $labels.namespace }} on {{ $labels.instance }} is experiencing CPU throttling at {{ $value | printf \"%.2f\" }}s/s for more than 2 minutes."
      # Container File Descriptor Alerts
      - alert: ContainerHighFileDescriptorUsage
        expr: (container_file_descriptors{job="cadvisor", environment="prod", namespace=~"prod-.*", container!~"redis.*|test.*"} / container_ulimits_soft{job="cadvisor", environment="prod", namespace=~"prod-.*", container!~"redis.*|test.*"}) * 100 > 80 and container_ulimits_soft{job="cadvisor", environment="prod", namespace=~"prod-.*", container!~"redis.*|test.*"} > 0
        for: 2m  
        labels:
          severity: warning
          service: container-monitoring
        annotations:
          summary: "Container {{ $labels.container }} high file descriptor usage"
          description: "Container {{ $labels.container }} in namespace {{ $labels.namespace }} on {{ $labels.instance }} has file descriptor usage at {{ $value | printf \"%.2f\" }}% for more than 2 minutes."
      # Container Socket Usage Alerts
      - alert: ContainerHighSocketUsage
        expr: container_sockets{job="cadvisor", environment="prod", namespace=~"prod-.*", container!~"redis.*|test.*"} > 1000
        for: 2m  
        labels:
          severity: warning
          service: container-monitoring
        annotations:
          summary: "Container {{ $labels.container }} high socket usage"
          description: "Container {{ $labels.container }} in namespace {{ $labels.namespace }} on {{ $labels.instance }} has {{ $value | printf \"%.0f\" }} open sockets for more than 2 minutes."

  - name: container_security_alerts
    rules:
      # Container Security Alerts
      - alert: ContainerRunningAsRoot
        expr: container_processes{job="cadvisor", environment="prod", namespace=~"prod-.*", container!~"redis.*|test.*", user="root"} > 0
        for: 15s  
        labels:
          severity: warning
          service: container-monitoring
        annotations:
          summary: "Container {{ $labels.container }} running as root"
          description: "Container {{ $labels.container }} in namespace {{ $labels.namespace }} on {{ $labels.instance }} has {{ $value | printf \"%.0f\" }} processes running as root user."
      # Container Privilege Escalation
      - alert: ContainerPrivilegedMode
        expr: container_spec_memory_limit_bytes{job="cadvisor", environment="prod", namespace=~"prod-.*", container!~"redis.*|test.*"} == 0 and container_spec_cpu_quota{job="cadvisor", environment="prod", namespace=~"prod-.*", container!~"redis.*|test.*"} == 0
        for: 15s  
        labels:
          severity: warning
          service: container-monitoring
        annotations:
          summary: "Container {{ $labels.container }} running without resource limits"
          description: "Container {{ $labels.container }} in namespace {{ $labels.namespace }} on {{ $labels.instance }} is running without CPU or memory limits, posing a security risk."
