---
# defaults file for postgres
# NOTE: Some variables must be set in your playbook or inventory (see playbook example)

postgres_instance_name: test

postgres_base_dir: "/data/{{ project_name }}/{{ postgres_instance_name }}"
postgres_data_dir: "{{ postgres_base_dir }}/data"
postgres_config_dir: "{{ postgres_base_dir }}/config"
postgres_log_dir: "{{ postgres_base_dir }}/log"

postgres_user: postgres
# postgres_password: ""  # Set in playbook or inventory (REQUIRED)
postgres_db: postgres
postgres_port: 5432
postgres_cpu_limit: "1"
postgres_mem_limit: "2g" 