---
# Set timezone to UTC
- name: Set timezone to UTC
  timezone:
    name: UTC
  become: true

# Install NTP package
- name: Install NTP package
  package:
    name: chrony
    state: present
  become: true

# Configure NTP servers
- name: Configure NTP servers
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: restart chronyd

# Setup system configuration
- name: Setup system configuration
  block:
    # Enable and start chronyd service
    - name: Enable and start chronyd service
      systemd:
        name: chronyd
        state: started
        enabled: yes
      become: true

    # Install locales package
    - name: Install locales package
      package:
        name: locales
        state: present
      become: true

    # Set system locale
    - name: Set system locale
      locale_gen:
        name: "{{ system_locale }}"
        state: present
      become: true

    # Update system locale
    - name: Update system locale
      command: update-locale LANG={{ system_locale }}
      become: true

    # Set system hostname
    - name: Set system hostname
      hostname:
        name: "{{ inventory_hostname }}"
      become: true
  when: not ansible_check_mode 