---
# tasks file for alloy

- name: Setup Alloy
  block:
    - name: Ensure Docker is running
      systemd:
        name: docker
        state: started
        enabled: true
      become: true

    - name: Ensure monitoring network exists
      community.docker.docker_network:
        name: "{{ alloy_network_name }}"
        state: present
      become: true

    - name: Setup Alloy user and directories (standardized)
      include_tasks: "{{ role_path }}/../common/tasks/setup_service_user.yml"
      vars:
        service_name: "alloy"
        service_user: "{{ alloy_user }}"
        service_group: "{{ alloy_group }}"
        service_directories:
          - "{{ alloy_data_dir }}"
        directory_mode: "0755"


  when: not ansible_check_mode

- name: Deploy alloy config
  template:
    src: config.alloy.j2
    dest: "{{ alloy_data_dir }}/config.alloy"
    owner: "{{ alloy_user }}"
    group: "{{ alloy_group }}"
    mode: '0644'
  become: true

- name: Deploy docker-compose.yml for alloy
  template:
    src: docker-compose.yml.j2
    dest: "{{ alloy_data_dir }}/docker-compose.yml"
    owner: "{{ alloy_user }}"
    group: "{{ alloy_group }}"
    mode: '0644'
  become: true
  tags: [configure, deploy]

- name: Deploy Alloy with standardized Docker Compose
  include_tasks: "{{ role_path }}/../common/tasks/docker_compose_deploy.yml"
  vars:
    compose_project_name: "alloy"
    compose_project_src: "{{ alloy_data_dir }}"
    compose_pull: true
    compose_remove_orphans: true
  when: not ansible_check_mode
  tags: [deploy, start] 