---
# handlers file for grafana

- name: restart grafana
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_data_dir }}"
    state: present
    restarted: true
  become: true
  listen: restart grafana
  when: not ansible_check_mode

- name: stop grafana
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_data_dir }}"
    state: absent
  become: true
  listen: stop grafana
  when: not ansible_check_mode

- name: start grafana
  community.docker.docker_compose_v2:
    project_src: "{{ grafana_data_dir }}"
    state: present
  become: true
  listen: start grafana
  when: not ansible_check_mode 