---
# defaults file for blackbox_exporter

blackbox_exporter_image: "prom/blackbox-exporter:latest"
blackbox_exporter_container_name: "blackbox_exporter"
blackbox_exporter_data_dir: "/opt/monitoring/blackbox_exporter"
blackbox_exporter_user: "blackbox_exporter"
blackbox_exporter_group: "blackbox_exporter"
blackbox_exporter_ports:
  - "9115:9115"
blackbox_exporter_volumes:
  - "{{ blackbox_exporter_data_dir }}/blackbox.yml:/etc/blackbox_exporter/config.yml:ro"
blackbox_exporter_command:
  - '--config.file=/etc/blackbox_exporter/config.yml'

# Website endpoint monitoring configuration
blackbox_enable_website_monitoring: true

# Blackbox targets for Prometheus monitoring
blackbox_targets:
  - https://google.com

# Endpoint configuration - can be defined as variables or loaded from config file
blackbox_endpoints_config_file: "{{ blackbox_exporter_data_dir }}/endpoints.yml"

# Comprehensive list of publicly accessible sites for monitoring
blackbox_endpoints:
  # Main Production Websites
  - name: "projectdot-work"
    url: "https://projectdot.work"
    module: "http_2xx"
    interval: "30s"
    timeout: "10s"
    headers:
      User-Agent: "Prometheus/Blackbox Exporter"
    valid_status_codes: [200, 201, 202, 301, 302]
  
  - name: "monitoring-projectdot-work"
    url: "https://monitoring.projectdot.work"
    module: "http_2xx"
    interval: "30s"
    timeout: "10s"
    headers:
      User-Agent: "Prometheus/Blackbox Exporter"
    valid_status_codes: [200, 201, 202, 301, 302]

 


# Prometheus integration paths (referenced from prometheus role)
blackbox_exporter_prometheus_config_dir: "/opt/monitoring/prometheus/config"
blackbox_exporter_prometheus_data_dir: "/opt/monitoring/prometheus"
blackbox_exporter_prometheus_user_id: "65533"
blackbox_exporter_prometheus_group_id: "65533" 