---
# handlers file for alloy

- name: restart alloy
  community.docker.docker_compose_v2:
    project_name: "alloy"
    project_src: "{{ alloy_data_dir }}"
    restarted: true
  become: true
  listen: restart alloy
  when: not ansible_check_mode

- name: stop alloy
  community.docker.docker_compose_v2:
    project_name: "alloy"
    project_src: "{{ alloy_data_dir }}"
    state: present
    stopped: true
  become: true
  listen: stop alloy
  when: not ansible_check_mode

- name: start alloy
  community.docker.docker_compose_v2:
    project_name: "alloy"
    project_src: "{{ alloy_data_dir }}"
    state: present
  become: true
  listen: start alloy
  when: not ansible_check_mode 