---
# Jenkins deployment verification tasks
# These tasks verify that Jenkins is properly deployed and functioning

- name: Verify Jenkins container health
  community.docker.docker_container_info:
    name: "{{ jenkins_container_name }}"
  register: jenkins_health_info
  failed_when: 
    - not jenkins_health_info.exists
    - jenkins_health_info.container.State.Status != "running"

- name: Check Jenkins login page accessibility
  uri:
    url: "https://{{ jenkins_domain }}/login"
    method: GET
    status_code: 200
    validate_certs: "{{ jenkins_verify_ssl_certs | default(false) }}"
  register: jenkins_login_check
  retries: 5
  delay: 10

- name: Wait for Jenkins to be fully ready
  uri:
    url: "https://{{ jenkins_domain }}/api/json"
    method: GET
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password | default('changeme') }}"
    force_basic_auth: yes
    status_code: 200
    validate_certs: "{{ jenkins_verify_ssl_certs | default(false) }}"
  register: jenkins_readiness_check
  retries: 10
  delay: 15
  until: jenkins_readiness_check.status == 200
  ignore_errors: true

- name: Verify Jenkins API with authentication
  uri:
    url: "https://{{ jenkins_domain }}/api/json"
    method: GET
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password | default('changeme') }}"
    force_basic_auth: yes
    status_code: 200
    validate_certs: "{{ jenkins_verify_ssl_certs | default(false) }}"
  register: jenkins_api_check
  when: jenkins_readiness_check.status is defined and jenkins_readiness_check.status == 200

- name: Verify no critical errors in recent logs
  command: docker logs {{ jenkins_container_name }} --tail 20
  register: jenkins_recent_logs
  changed_when: false
  failed_when: 
    - "'SEVERE' in jenkins_recent_logs.stdout"
    - "'Permission denied' in jenkins_recent_logs.stdout"

- name: Display verification success
  debug:
    msg:
      - "✅ Jenkins verification completed successfully"
      - "Container: {{ jenkins_container_name }} ({{ jenkins_health_info.container.State.Status }})"
      - "Login Page: Accessible ({{ jenkins_login_check.status }})"
      - "API: {{ 'Authenticated access working (' + (jenkins_api_check.status|string) + ')' if jenkins_api_check.status is defined else 'Not yet ready - may need more time' }}"
      - "Logs: No critical errors detected"
  when: jenkins_verification_enabled | default(false)
