---
# Cleanup tasks for remote monitoring
# This file should be included when hosts are removed from monitoring

- name: Remove target file for this host
  file:
    path: "{{ prometheus_config_dir }}/targets/{{ inventory_hostname }}_nginx.yml"
    state: absent
  delegate_to: "{{ monitoring_server_host }}"
  run_once: true
  when: monitoring_server_host is defined

- name: Cleanup nginx_exporter resources
  block:
    - name: Remove nginx_exporter with standardized Docker Compose
      include_tasks: "{{ role_path }}/../common/tasks/docker_compose_deploy.yml"
      vars:
        compose_project_name: "nginx_exporter"
        compose_project_src: "{{ nginx_exporter_data_dir }}"
        compose_state: "absent"  # Remove the service
      when: nginx_exporter_data_dir is defined

    - name: Remove nginx_exporter data directory
      file:
        path: "{{ nginx_exporter_data_dir }}"
        state: absent
      become: true
      when: nginx_exporter_data_dir is defined
  when: not ansible_check_mode

- name: Reload Prometheus configuration after cleanup
  uri:
    url: "http://localhost:9090/-/reload"
    method: POST
    status_code: [200]
  delegate_to: "{{ monitoring_server_host }}"
  run_once: true
  failed_when: false
  changed_when: false
  when: monitoring_server_host is defined 