---
# Deploy Nginx Exporter

- name: Deploy docker-compose.yml for nginx_exporter
  template:
    src: docker-compose.yml.j2
    dest: "{{ nginx_exporter_data_dir }}/docker-compose.yml"
    owner: "{{ nginx_exporter_user }}"
    group: "{{ nginx_exporter_group }}"
    mode: '0644'
  become: true
  notify: restart nginx_exporter

- name: Setup and manage nginx_exporter container
  block:
    - name: Deploy nginx_exporter with standardized Docker Compose
      include_tasks: "{{ role_path }}/../common/tasks/docker_compose_deploy.yml"
      vars:
        compose_project_name: "nginx_exporter"
        compose_project_src: "{{ nginx_exporter_data_dir }}"
        compose_pull: true
        compose_remove_orphans: true
        compose_recreate: "always"  # Force recreate to ensure clean deployment
      notify: restart nginx_exporter

    - name: Wait for nginx_exporter to be ready
      ansible.builtin.uri:
        url: "http://localhost:{{ nginx_exporter_port }}/metrics"
        method: GET
        status_code: 200
      register: nginx_exporter_ready
      retries: 10
      delay: 5
      until: nginx_exporter_ready.status == 200
      changed_when: false

    - name: Verify nginx_exporter metrics endpoint
      ansible.builtin.uri:
        url: "http://localhost:{{ nginx_exporter_port }}/metrics"
        method: GET
        status_code: 200
        return_content: true
      register: nginx_exporter_metrics
      changed_when: false

    - name: Verify nginx_exporter can scrape nginx stub_status
      ansible.builtin.uri:
        url: "http://localhost:{{ nginx_exporter_port }}/metrics"
        method: GET
        status_code: 200
        return_content: true
      register: nginx_exporter_scrape_check
      retries: 3
      delay: 5
      until: nginx_exporter_scrape_check.status == 200
      changed_when: false
  when: not ansible_check_mode 